### ISSUE TITLE
ImportError after pip installing

### ISSUE THREAD

**Issue by dannydb** [onyxfish/clan#25]
I get this error after installing with pip:

```
± ddebelius at localdev in [civilrights].../civilrights on master:debb5 ✗
$ pip install clan
Downloading/unpacking clan
  Downloading clan-0.1.3.tar.gz
  Running setup.py (path:/Users/ddebelius/.virtualenvs/civilrights/build/clan/setup.py) egg_info for package clan

Requirement already satisfied (use --upgrade to upgrade): google-api-python-client==1.2 in /Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages (from clan)
Requirement already satisfied (use --upgrade to upgrade): httplib2==0.9 in /Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages (from clan)
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in /Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages (from clan)
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.7.3 in /Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages (from clan)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages (from Jinja2==2.7.3->clan)
Installing collected packages: clan
  Running setup.py install for clan

    Installing clan script to /Users/ddebelius/.virtualenvs/civilrights/bin
Successfully installed clan
Cleaning up...
± ddebelius at localdev in [civilrights].../civilrights on master:debb5 ✗
$ which clan
/Users/ddebelius/.virtualenvs/civilrights/bin/clan
± ddebelius at localdev in [civilrights].../civilrights on master:debb5 ✗
$ clan
Traceback (most recent call last):
  File "/Users/ddebelius/.virtualenvs/civilrights/bin/clan", line 9, in <module>
    load_entry_point('clan==0.1.3', 'console_scripts', 'clan')()
  File "/Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages/pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "/Users/ddebelius/.virtualenvs/civilrights/lib/python2.7/site-packages/pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named clan
```

**Comment by onyxfish** [comment]
Resolved in f2c9d960a3f62a7d7850691867e71d2b3c589f80
